name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Note 13/main.tex
          latexmk_use_lualatex: true
          work_in_root_file_dir: true
          continue_on_error: true
          latexmk_shell_escape: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: Note 13/main.pdf
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: main.pdf
          repo-token: ${{ secrets.GITHUB_TOKEN }}
